function dydt = nodrugfructoseODE(t, y, p)
    
    GI_chol = y(1);
    peripheral_chol = y(2);
    liver_chol = y(3);
    clearance_chol = y(4);

    GI_TG = y(5);
    peripheral_TG = y(6);
    liver_TG = y(7);
    clearance_TG = y(8);

    ROS = y(9);
    oxLDL = y(10);
    fructose = y(11);  % New glucose variable

    % GI cholesterol dynamics
    dGI_chol = -p.V.GI * p.GI.chylomicron.chol * GI_chol;

    % GI triglyceride dynamics
    dGI_TG = -p.V.GI * p.GI.chylomicron.TG * GI_TG;
    
    % Peripheral cholesterol dynamics with glucose influence
    dperipheral_chol = (...
        + p.V.GI * p.GI.chylomicron.chol * GI_chol ...
        + p.V.liver * p.liver.LDL.chol * liver_chol * ROS ...
        + p.V.liver * p.liver.HDL.chol * liver_chol ...
        - p.V.peripheral * p.peripheral.LDL.chol * peripheral_chol ...
        - p.V.peripheral * p.peripheral.chylomicron.chol * peripheral_chol ...
        - p.V.peripheral * p.peripheral.HDL.chol * peripheral_chol * (1 / ROS) ...
        - p.V.peripheral * p.peripheral.clearance.chol * peripheral_chol ...
        ) / p.V.peripheral;

    % Peripheral triglyceride dynamics
   dperipheral_TG = (...
    + p.V.GI * p.GI.chylomicron.TG * GI_TG ...
    + p.V.liver * p.liver.LDL.chol * liver_chol ...
    + p.V.liver * p.liver.HDL.chol * liver_chol ...
    - p.V.peripheral * p.peripheral.chylomicron.TG * peripheral_TG ...
    - p.V.peripheral * p.peripheral.HDL.TG * peripheral_TG ...
    - p.V.peripheral * p.peripheral.clearance.TG * peripheral_TG ...
    + p.fructose.TG_effect * fructose ... % Fructose effect on TG synthesis
    ) / p.V.peripheral;

    % Liver cholesterol dynamics with glucose influence
    dliver_chol = (...
    + p.V.peripheral * p.peripheral.chylomicron.chol * peripheral_chol ...
    + p.V.peripheral * p.peripheral.HDL.chol * peripheral_chol * (1 / ROS) ...
    + p.V.peripheral * p.peripheral.clearance.chol * peripheral_chol ...
    + p.V.peripheral * p.peripheral.LDL.chol * peripheral_chol ...
    - p.V.liver * p.liver.LDL.chol * liver_chol * ROS ...
    - p.V.liver * p.liver.HDL.chol * liver_chol ...
    - p.V.liver * p.liver.clearance.chol * liver_chol ...
    - p.V.liver * p.liver.oxLDL.chol * liver_chol * ROS ...
    + p.fructose.liver_effect * fructose ... % Fructose effect on liver cholesterol synthesis
    ) / p.V.liver;

    % Liver triglyceride dynamics
    dliver_TG = (...
        + p.V.peripheral * p.peripheral.chylomicron.TG * peripheral_TG ...
        + p.V.peripheral * p.peripheral.HDL.TG * peripheral_TG ...
        + p.V.peripheral * p.peripheral.clearance.TG * peripheral_TG ...
        - p.V.liver * p.liver.LDL.TG * liver_TG ...
        - p.V.liver * p.liver.HDL.TG * liver_TG ...
        - p.V.liver * p.liver.clearance.TG * liver_TG ...
        ) / p.V.liver;

    % Cholesterol clearance dynamics
    dclearance_chol = (...
    + p.V.peripheral * p.peripheral.clearance.chol * peripheral_chol ...
    + p.V.liver * p.liver.clearance.chol * liver_chol ...
    - p.fructose.clearance_effect * fructose ... % Fructose reduces clearance efficiency
    );

    % Triglyceride clearance dynamics
    dclearance_TG = (...
        + p.V.peripheral * p.peripheral.clearance.TG * peripheral_TG ...
        + p.V.liver * p.liver.clearance.TG * liver_TG ...
        );

    % ROS dynamics with glucose effect
   dROS = (...
    + p.basalROS * ROS * p.foodProductionMultiplier ...
    - p.antioxidant * ROS * p.foodAntiOxMultiplier ...
    + p.fructose.ROS_effect * fructose ... % Fructose effect on ROS production
    );

    % Oxidized LDL dynamics
    doxLDL = p.V.liver * p.liver.oxLDL.chol * liver_chol * ROS; 
    
    % Glucose dynamics (optional: glucose regulation)
    dfructose = -p.fructose.consumption_rate * fructose; % Glucose consumption

    % Assemble the ODEs
    dydt = [...
        dGI_chol; dperipheral_chol; dliver_chol; dclearance_chol; ...
        dGI_TG; dperipheral_TG; dliver_TG; dclearance_TG; ...
        dROS; doxLDL; dfructose ...
        ];
end
